version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    environment:
      - API_URL=https://middleware-server-app.onrender.com/api/users
    networks:
      - app-network

networks:
  app-network:
    driver: bridge